import React from "react";
import RiskGauge from "./RiskGauge.jsx";

export default function ExplanationResults({ items, failed }) {
  if ((!items || items.length === 0) && (!failed || failed.length === 0)) return null;

  return (
    <div className="panel section-gap">
      <div className="panel-title">Explanation</div>

      <div className="explanation-list">
        {items.map((e, i) => (
          <div className="explanation-card" key={e.binary_name || i}>
            <div className="risk-result-top">
              <div>
                <div className="binary-result-name mono">{e.binary_name}</div>
                <div className="predicted-algo-sm" style={{ marginTop: 6 }}>
                  {e.algorithm} <span className="context-item-label" style={{ display: "inline" }}>· {e.algorithm_family}</span>
                </div>
                <div className="generated-by-tag mono">
                  generated by: {e.generated_by}
                  {e.generation_time_ms != null && ` · ${(e.generation_time_ms / 1000).toFixed(1)}s`}
                </div>
              </div>
              <RiskGauge score={e.risk_score} level={e.risk_level} />
            </div>

            <p className="explanation-summary">{e.summary}</p>

            {e.sections &&
              Object.entries(e.sections).map(([title, text]) => (
                <div className="explanation-section" key={title}>
                  <div className="explanation-section-title">{title}</div>
                  <div className="explanation-section-body">{text}</div>
                </div>
              ))}

            {e.references && e.references.length > 0 && (
              <div className="citation-chips">
                {e.references.map((ref) => (
                  <span className="citation-chip" key={ref}>
                    {ref}
                  </span>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>

      {failed && failed.length > 0 && (
        <div className="error-banner section-gap">
          {failed.length} binary(ies) failed explanation:{" "}
          {failed.map((f) => f.binary_name || f.error).join(", ")}
        </div>
      )}
    </div>
  );
}
