"""Add uploaded_features table

Revision ID: 9ec6d1939eb1
Revises: 16a6bfdcaf8d
Create Date: 2026-08-04 02:19:09.423645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ec6d1939eb1'
down_revision: Union[str, Sequence[str], None] = '16a6bfdcaf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firmware_id', sa.Integer(), nullable=False),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firmware_id'], ['firmware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_features_id'), 'uploaded_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_features_id'), table_name='uploaded_features')
    op.drop_table('uploaded_features')
    # ### end Alembic commands ###
