"""Add storage_path to firmware table

Revision ID: fca94be7c6d4
Revises: 9ec6d1939eb1
Create Date: 2026-08-05 01:12:22.013469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca94be7c6d4'
down_revision: Union[str, Sequence[str], None] = '9ec6d1939eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firmware', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('firmware_file_hash_key'), 'firmware', type_='unique')
    op.create_index(op.f('ix_firmware_file_hash'), 'firmware', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firmware_file_hash'), table_name='firmware')
    op.create_unique_constraint(op.f('firmware_file_hash_key'), 'firmware', ['file_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('firmware', 'storage_path')
    # ### end Alembic commands ###
